
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hackfest_development

test:
  <<: *default
  database: hackfest_test

production:
  <<: *default
  database: hackfest_production
  password: <%= ENV['HACKFEST_DATABASE_PASSWORD'] %>
